execute pathogen#infect()

" Yeah, I totally do want you to back up over that
set backspace=indent,eol,start

" Set F5 to insert timestamp
nnoremap <F5> "=strftime("%c")<CR>P
inoremap <F5> <C-R>=strftime("%c")<CR>

" set syntax highlighting if we have color or gui
if &t_Co >= 256 || has('gui_running')
  syntax on
  set background=dark
  colorscheme solarized
  autocmd! BufEnter
  set guifont=DejaVu\ Sans\ Mono:h14
endif

" enable filetype and plugins
filetype on
filetype indent on
filetype plugin on

" set options here
set number
set pastetoggle=<F8>
set ai           " auto indend
set si           " smart indent
set ff=unix      " file format unix dammit
set nocompatible " nocompatible mode
set ruler        " ruler the bottom

set expandtab     " expand tabs to spaces
set tabstop=2     " define what our tabs are
set softtabstop=2 " soft tabstop
set shiftwidth=2  " # of spaces for auto indent
set smarttab      " smart tab (shiftwidth v tabstop)
set tw=0          " no textwidth set by default
set noshowmode
set modeline      " enable modelines
set modelines=3   " number of modelines to read
set tildeop       " case change with movement rather than single char

set showmatch       " show matching brackets
set matchtime=5     " how many tenths of a second to blink matching brackets for

set hlsearch    " highlight search on by default

set noincsearch   " move cursor as you type search terms
set autoread            " auto read in files that have changed underneath
set shellcmdflag=-lc  " set the ! shell to be a login shell to get at functions and aliases
let g:vim_markdown_folding_disabled=1

"====[ Make the 81st column"standout"]==========================================
let &colorcolumn=join(range(81,999),",")
let &colorcolumn="80,".join(range(480,999),",")
highlight ColorColumn ctermbg=232 guibg=#2c2d27
"call matchadd('ColorColumn', '\%81v', 100)

"====[ Make tabs, trailing whitespace, and non-breaking spaces visible"]========
exec "set listchars=trail:\uB7,nbsp:~"
set list

"====[ Highlight the entire line when jumping through matches"]=================
nnoremap <silent> n   n:call HLNext(0.1)<cr>
nnoremap <silent> N   N:call HLNext(0.1)<cr>

function! HLNext (blinktime)
  set invcursorline
  redraw
  exec 'sleep ' . float2nr(a:blinktime * 1000) . 'm'
  set invcursorline
  redraw
endfunction

"====[ Swap v and CTRL-V, because Block mode is more useful that Visual mode"]==
nnoremap    v   <C-V>
nnoremap <C-V>     v

vnoremap    v   <C-V>
vnoremap <C-V>     v

